---
title: "Laliga_2324"
author: "loveloveup"
date: "2023-10-01"
output: html_document
output:
  html_document:
    toc: TRUE             
    toc_depth: 3          
    toc_float: TRUE       
    number_sections: TRUE 
    highlight: monochrome 
    theme: flatly       
    code_folding: hide    
    md_extensions: "+ignore_line_breaks" 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install packages 
library(tidyverse)
library(ggrepel)
library(worldfootballR)
library(formattable)


# dataset
Laliga_2023 <- understat_league_match_results(league = "La liga",
                                         season_start_year = 2023)
Laliga_2023 <- tibble(Laliga_2023)

Laliga_2023_match <- understat_league_match_results(league = "La liga",
                                         season_start_year = 2023)
Laliga_2023_match <- tibble(Laliga_2023_match)

```

# data summary

```{r}
Laliga_2023 |> 
  glimpse()
Laliga_2023 |> 
  head() |> view()

# wide to long
Laliga_2023 <- Laliga_2023 |> 
  pivot_longer(cols = c(home_team,away_team),
               names_to = "home_away",
               values_to = "team") |>
  mutate(win = if_else(home_goals > away_goals,"home_team",
                       if_else(home_goals == away_goals,"draw","away_team")),
         point = if_else(home_away == win,3,
                         if_else(win == "draw",1,0))) |> 
  mutate(G = if_else(home_away == "home_team",home_goals,away_goals),
         GA = if_else(home_away == "home_team",away_goals,home_goals),
         xG = if_else(home_away == "home_team",home_xG,away_xG),
         xGA = if_else(home_away == "home_team",away_xG,home_xG)) 

```

## ranking
```{r}
Ranking <- Laliga_2023 |> 
  group_by(team) |> 
  summarise(points = sum(point),
            G = sum(G),
            xG = sum(xG)) |> 
  arrange(desc(points))
DT::datatable(Ranking,
              extensions = "Buttons",
              options = list(
                pageLength = 20,
                buttons = c("copy", "csv", "excel", "pdf", "print")
              ))



top_10 <- Ranking |> 
  head(10) |> 
  pull(team)


# ランキング推移
g <- Laliga_2023 |> 
  select(team,datetime,point) |> 
  group_by(team) |> 
  mutate(points = cumsum(point)) |> 
  filter(team %in% c(top_10)) |> 
  ggplot(aes(datetime,points, group = 1, color = team)) +
  geom_line()
plotly::ggplotly(g)

```


# 得点、期待値分析
## xG_xGA
ゴール期待値と被ゴール期待値の分布

```{r}
Laliga_2023 |> 
  group_by(team) |> 
  summarise(xG = sum(xG),
            xGA = sum(xGA)) |> 
  ggplot(aes(xG,xGA, color = team, label = team)) + 
  geom_point()+
  geom_abline(slope = 1)+
  ggrepel::geom_label_repel()

```


## G_xG
実際のゴール数とゴール期待値の分布（累計）

```{r}
Laliga_2023 |> 
  group_by(team) |> 
  summarise(G = sum(G),
            xG = sum(xG),
            xGA = sum(xGA)) |> 
  ggplot(aes(xG,G, color = team, label = team)) + 
  geom_point()+
  geom_abline(slope = 1)+
  ggrepel::geom_label_repel()
```

# Laligaプレイヤーの分析
## xGとG数のplot
```{r}
LaLiga_shot_location <- 
  understat_league_season_shots(league = "La liga",season_start_year = 2022)
LaLiga_shot_location <- tibble(LaLiga_shot_location) |> 
  mutate(minute = as.double(minute))
# Goal&xG 決定力比較
LaLiga_shot_location |> 
  group_by(player) |>
  summarise(G = sum(str_detect(result,"Goal")),
            xG = sum(xG)) |> 
  arrange(desc(G)) |> 
  ggplot(aes(xG,G))+
  geom_point()+
  geom_abline(slope = 1)+
  geom_text_repel(aes(label = player))+
  xlim(c(0,10))+
  ylim(c(0,10))

LaLiga_shot_location |> 
  glimpse()
```



# Barcelona分析
## 個人分析
ペドリの存在
ペドリの出場時と欠場時のｘG、得点、勝ち点の比較
→データで、なんの試合に出場したのか不明なためできなそう
```{r}
raheem_sterling_shots <- understat_player_shots(player_url = "https://understat.com/player/618")
dplyr::glimpse(raheem_sterling_shots)
```

##チーム分析
```{r}
Barcelona_team_players_2020_2023 <- 
  understat_team_players_stats(team_url = 
                               c("https://understat.com/team/Barcelona/2023",
                                 "https://understat.com/team/Barcelona/2022",
                                 "https://understat.com/team/Barcelona/2021",
                                 "https://understat.com/team/Barcelona/2020"))
dplyr::glimpse(Barcelona_team_players_2020_2023)

#シーズンを通した平均的なパフォーマンスの比較
Barcelona_team_players_2020_2023 |> 
  group_by(player_name,season) |> 
  summarise(time = sum(time),
            G = sum(goals),
            xG = sum(xG),
            A = sum(assists),
            key_passes = sum(key_passes),
            yellow_cards = sum(yellow_cards),
            G90 = G/time*90,
            xG90 = xG/time*90,
            A90 = A/time*90,
            KP90 = key_passes/time*90) |> 
  filter(time > 300)|> view()

#監督比較



```



##ゴール時間帯
ポゼッションが強いチームは後半のタイミングで点がとれる？

```{r}
LaLiga_shot_location |> 
  filter(result == "Goal",
         h_a == "h" & home_team == "Barcelona"|
         h_a == "a" & away_team == "Barcelona") |> 
  ggplot(aes(x = minute))+
  geom_histogram(binwidth = 5)

```

##黄金期と比べて
###
ポゼッション


## 守備陣の評価

## 監督交代の影響


## 得失点分析

##トランジション
### トランジションの多さ
### トランジションへの貢献度




